import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/navBar";
import { SignIn } from "@/app/_components/signIn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={[inter.className, "dark:bg-background", "bg-background"].join(" ")}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
